### PR TITLE
 Option to automatically allow traffic from all local ip addresses 

### PR DESCRIPTION
**Pull request by ccbur**
Convenient function to allow traffic from all local ip addresses ("--allowlocal"). The Windows IP Helper application programming interface is used to query all interface adapters with their ip addresses. To relieve resource allocation a refresh is done every 30 seconds when a new request is coming in. This is very useful in case of dynamic ips and/or switching of interfaces (vpn, wifi, lan, etc.).

I think this should work also with older environments (Python 2.x, Windows XP, etc.), but I only tested it on Python 3 and Windows 7 / 10.

### CODE REVIEW

**Comment by genotrance** [comment]
Some comments:-
- It seems --allow=* and --allowlocal should coexist so someone could run Px in gateway mode and allow all local addresses using this new code as well as a few external IPs if they so desired. If --allowlocal overrides --allow then there's no way to accomplish this.
- Isn't there a simpler way to get all local IPs? The following seems to work.
```python
socket.getaddrinfo(socket.gethostname(), 80)
```

**Comment by ccbur** [comment]
Good points. Obviously I missed socket.getaddrinfo().  :-(

I'll look into this next week.

**Comment by ccbur** [comment]
Implementation is almost ready, but I'm struggling how --allow and --allowlocal should work together in a default way. Default value for --allow is currently *.*.*.*, so if you don't specify --allow, then all traffic will be allowed, no matter which ip addresses --allowlocal will discover. 

To give this some sense, I think the default value for --allow would need to change depending on --allowlocal. If --allowlocal is set, a default value for --allow should be 0.0.0.0/0, so only local traffic will be allowed, but not external. Of course you can always override this default value with the --allow parameter.

Nevertheless I don't like changing default values depending on other parameters. The documentation must reflect this and it's not easy to understand.

Any idea?

**Comment by ccbur** [comment]
I tried to document this. Seems to work out... :-)

**Comment by ccbur** [comment]
I'm struggling for two days now with the term --local. I know that I introduced this word (allow**local**), but the term "local" does not really fit in. There is a reason why "**local**host" means "127.0.0.1" and not all the other interfaces on your system. So in general "local" has a special meaning and "allowlocal" or "local" are not really referring to this.

Maybe we should rename the parameter to "--host"? You could read this parameter in a "more than localhost, but not the rest of the world" way... What do you think?  

After your 0.3 release I see why you offered to integrate this change by yourself instead of using this PR :-) Nice job... I'm fine with it!!!

**Comment by genotrance** [comment]
I agree --local is misleading, but --host is just as confusing. There's no standard word for this that I could find. I presume it's mainly useful for your [Docker](https://github.com/genotrance/px/pull/16) use case since in my VM scenario, my VM get's a 169.x.x.2 IP whereas the host side is 169.x.x.1 so just adding .1 won't work. I need to add the subnet or specific VM IPs too. I guess that's because I'm using bridge mode but if I had a NAT, it would probably work the way you have it configured with Docker.

Thinking further, I was wondering how useful this feature really is - the internal networks from Docker and VMs don't really change unlike a LAN/VPN. What's the benefit of dynamically scanning the IPs if the ones we are trying to address aren't really changing? I'm curious if I am not seeing something that you are encountering.

Some other meh ideas as far as names are concerned:-
- private
- self, this
- thishost
- hostonly
- bridge

Keeping the name aside, do you agree on the design in general?

**Comment by ccbur** [comment]
Believe me, this feature is useful :)

The internal network of Docker4Windows is not changing. It's all about the way the traffic passes through your machine and what traffic you want to allow and what to deny. 

A vSwitch forwards the traffic from the docker world to your host and everything outside via NAT. The containers are inside a VM, so from a containers perspective you cannot send px-traffic to 127.0.0.1, because this is your Linux VM and not the Windows host with a running px instance. So your environment uses something like https_proxy=your_local_ip:3128 and not https_proxy=127.0.0.1:3128. 
For this to work you need to configure px to listen on other interfaces, too, not only 127.0.01 ((--gateway or --listen="").

But if you do not want to open up your host as a forward proxy for everyone else in your network (that happens with --gateway or --listen=x.x.x.x), you need to restrict the source address to your local ip address also (that's the reason --allow is introduced). It's just a security precaution.

In the end two things are important:

1. Listen on your local primary IP interface (there might be multiple in your system and "primary" might change!)
2. Don't allow traffic originating from external IPs

But at least my local IP is changing very often (eg. VPN, WLAN/LAN switching, even changing buildings, because in our corporate environment, we have defined subnets for every building), so you would need to restart px, look at your local interfaces and reconfigure the --allow-Parameter. That's where I introduced --allowlocal (or whatever we call it), just for the sake of automation of this process. --allow and --allowlocal is just to block real external traffic. They are not needed to allow the docker traffic!

Docker would work ootb just with --gateway. But then your system can be misused :-(

Last but not least, for me --hostonly sounds very reasonable!!  :-)

**Comment by ccbur** [comment]
I tested the the --hostonly parameter and it works like expected. Thank you!

I'll close this PR and will migrate to your master.

**Pull request closed without merging**
