### PR TITLE
Enable non-windows platforms

### PR DESCRIPTION
**Pull request by kraag-gorim**
Hi,

I made an effort to try enable running px on non windows systems. Linux in my particular case. I mainly disabled functionality that is not available.
Let me know what you think.

Regards

### CODE REVIEW

**Comment by genotrance** [comment]
What's the point of this? It might run but does it even do anything? How will it do NTLM / Kerberos auth on Linux?

**Comment by kraag-gorim** [comment]
The point is to make a first step of enabling px usage on linux. Current version can neither be installed nor run on other systems than windows. My goal was to reach at least basic functionality and to work on authorization in the next one.

Feel to close this one if you don't see fit.

**Comment by genotrance** [comment]
Okay I appreciate the idea of doing this incrementally but I don't have a way of testing this and whether it breaks anything on Windows though. Do you have high confidence this will work and it has been tested?

**Comment by kraag-gorim** [comment]
Agreed. I am also limited to test this in a proper way.

**Pull request closed without merging**
