### PR TITLE
Add Automated Build System

### PR DESCRIPTION
**Pull request by wheelerlaw**
This is a sample of how to employ Travis CI to automate the release process for this project. It will build when a commit is pushed/merged into master, when a new tag is created (`vmajor.minor[.patch]` for releases and `YYYY-MM-DD` for pre-releases) and then the `vHEAD` tag is updated. The only thing that would need to be changed is you would need to add your own GitHub API token (mine is in there, but it won't do anything in your repository since it is encrypted and keyed by the source repo). You can generate the encrypted value with the Travis CLI (docs [here](here)).

I should note that this uses Wine to build px on Linux, instead of using Windows, resulting in a way faster build time.

### CODE REVIEW

**Comment by wheelerlaw** [comment]
You can see an example of this working on [my fork](https://github.com/wheelerlaw/px/releases) of the project:

image

**Comment by genotrance** [comment]
This is great! I'll integrate it over the weekend.

**Comment by wheelerlaw** [comment]
Cool. If you need any help with setting it up, feel free to reach out (via email or on the gitter app--I have it on my phone with notifications turned on).

**Comment by rrzaripov** [comment]
Why not to use [appveyor](https://www.appveyor.com/docs/windows-images-software/)? For Windows this is the best solution, free for open source projects. I have successfully experienced with Python based projects in appveyor. Also appveyor used by many projects on GitHub.

**Comment by wheelerlaw** [comment]
@rrzaripov Probably a way better idea. I just don't have any experience with it, so I'll have to do some research, unless you have some spare cycles to help out with that.

**Comment by genotrance** [comment]
I don't think moving to AppVeyor is warranted, considering most of the work is done already as far as deployment is concerned.

All that needs to be done with this travis.yml file is to switch to Windows, remove the wine related stuff and run build.bat instead.

**Comment by rrzaripov** [comment]
@genotrance unfortunately, Travis does not support Windows, so @wheelerlaw suggested to builds px using Wine under Linux. Appveyor, on the contrary, offers Windows as a platform for building (which is convenient for your project) and optionally, if a version for Linux will be implemented, it can be assembled in Travis or in Appveyor (they have recently added support for Linux) .
As for the transition, there is nothing complicated here, I am ready to assist and answer any questions. Including setup for tests runner, checks of PR and saving of assemblies and releases in GitHub.

**Comment by genotrance** [comment]
@rrzaripov - happy for your help, but Travis has added Windows support recently and I've been using it for a few months now. I'm not attached to either though and have used Windows on both so I'm open to either approach.

**Comment by rrzaripov** [comment]
@genotrance thanks for the info, you are absolutely right! I will read the documentation for Windows support in Travis.

**Comment by genotrance** [comment]
The main difference is that everything runs in git-bash instead of cmd on AppVeyor. Makes things easier cause cross-platform is easier but other things are more of a pain.

Regardless, I'm thrilled for any help since I'm spread quite thin and Px is not getting the attention it deserves.

**Comment by genotrance** [comment]
I've enabled CI on Travis for Windows. It runs a minimal test across multiple versions of Python using Miniconda. I will use the deploy portion from this PR to enable posting new releases at some point. Feel free to expand the CI capabilities and thanks for bringing this up.

https://travis-ci.org/genotrance/px

**Pull request closed without merging**
